# Orchestrator Agent Tools Configuration
# Handoff tools for routing to specialist agents

tools:
  - name: handoff_to_sql_agent
    type: function
    description: |
      Route the query to SqlAgent for database queries.
      Use this when the user asks about sales, orders, products, customers, invoices,
      or any question that requires querying the database.
      Returns the specialist agent's response.
    parameters:
      type: object
      properties:
        query:
          type: string
          description: The user's original query to be processed by SqlAgent
        reason:
          type: string
          description: Brief explanation of why this query should be handled by SqlAgent
      required:
        - query

  - name: handoff_to_web_agent
    type: function
    description: |
      Route the query to WebAgent for web search.
      Use this when the user asks about current events, news, latest information,
      market trends, or topics not available in the database.
      Returns the specialist agent's response.
    parameters:
      type: object
      properties:
        query:
          type: string
          description: The user's original query to be processed by WebAgent
        reason:
          type: string
          description: Brief explanation of why this query should be handled by WebAgent
      required:
        - query
